---
# system wide
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      ignore_errors: yes
      changed_when: False
  vars_files:
    - vars.yml
  tasks:
    - {include: tasks/packages.yml, tags: ['packages', 'apt']}

# user specific
- hosts: localhost
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml
  tasks:
    - {include: tasks/conda.yml, tags: ['conda']}
    - {include: tasks/aodn_chef.yml, tags: ['aodn', 'chef']}
    - {include: tasks/data_services.yml, tags: ['aodn', 'data_services']}
    - {include: tasks/github_repos.yml, tags: ['github','repos']}

# needs other packages to be installed first prior to run the following
- hosts: localhost
  connection: local
  become: true
  roles:
    - role: webarchitect609.jet_brains_toolbox
  vars_files:
    - vars.yml
