---
# user specific
- hosts: localhost
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml
  tasks:
    - {include: tasks/aodn_chef.yml, tags: ['aodn', 'chef']}
    - {include: tasks/data_services.yml, tags: ['aodn', 'data_services']}
    - {include: tasks/github_repos.yml, tags: ['github','repos']}
    - {include: tasks/conda.yml, tags: ['conda']}
