- name: create src directory
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{github_repo_dir}}/chef/src"
    state: directory
    mode: 0775

- name: clone repo "{{item.name}}"
  become: yes
  become_user: "{{user}}"
  git:
    repo: "{{item.url}}"
    dest: "{{github_repo_dir}}/chef/src/{{item.name}}"
    accept_hostkey: yes
    track_submodules: yes
    clone: yes
    update: no
  with_items:
    - { url: "{{repo_data_services}}", name: data-services }
  ignore_errors: true
